# Generated by Django 4.2.4 on 2023-08-30 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doggy_daycare', '0002_delete_choice_delete_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Owner First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Owner Last Name')),
                ('pet', models.CharField(max_length=120, verbose_name='Pet Name')),
                ('date', models.DateTimeField(verbose_name='Booking date')),
                ('number', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
